[env:pico_w]
platform = raspberrypi@1.19.0
board = rpipicow
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200

lib_deps =

build_flags =
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH=0
